inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'storage/**/*'
    - 'vendor/**/*'
    - 'app/controllers/concerns/action_controller/**/*'
    - 'app/models/custom_marc_writer.rb'

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    - 'app/services/marc_record_service.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*.builder'
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Layout/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'app/models/ability.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/ability.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/features/**/*'
