development:
  <% if ENV.include? "SIDEKIQ_REDIS_URL" %>
  adapter: redis
  url: <%= ENV.fetch("SIDEKIQ_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: aggregator_production
  <% else %>
  adapter: async
  <% end %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("SIDEKIQ_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: aggregator_production
