development:
  <% if ENV.include? "ACTION_CABLE_REDIS_URL" %>
  adapter: redis
  url: <%= ENV.fetch("ACTION_CABLE_REDIS_URL") { "redis://localhost:6379/2" } %>
  channel_prefix: aggregator_production
  <% else %>
  adapter: async
  <% end %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("ACTION_CABLE_REDIS_URL") { "redis://localhost:6379/2" } %>
  channel_prefix: aggregator_production
