jwt:
  secret: 'i♥️dolphins'
  algorithm: 'HS256'
sidekiq:
  logger_level: 'Logger::INFO' # The default from Sidekiq

action_mailer:
  default_options:
    from: 'test@example.com'

marc_fixture_seeds:
  host: https://pod.stanford.edu
  token: ''
  upload_count: 5
  organizations:
    - Cornell
    - Princeton
    - Stanford
