jwt:
  secret: 'i♥️dolphins'
  algorithm: 'HS256'
sidekiq:
  logger_level: 'Logger::INFO' # The default from Sidekiq

action_mailer:
  default_options:
    from: 'test@example.com'

marc_fixture_seeds:
  host: https://pod.stanford.edu
  token: ''
  upload_count: 5
  organizations:
    - Cornell
    - Princeton
    - Stanford

# refer to https://icons.getbootstrap.com/ for icon class names
metadata_status:
  success:
    icon_class: 'file-earmark-fill'
    label: 'Valid MARC'
  deletes:
    icon_class: 'file-earmark-excel-fill'
    label: 'Deletes'
  invalid:
    icon_class: 'exclamation-circle-fill'
    label: 'Invalid MARC'
  not_marc:
    icon_class: 'exclamation-triangle-fill'
    label: 'Neither MARC nor Deletes'
  unknown:
    icon_class: 'question-circle-fill'
    label: 'Unknown'
